//startLoadingScreen ["WAIT",""];

TEST_IncludedAuthors =
[
	"[TF]Nkey",
	"Anitsoy",
	"AWAR & [TF]Nkey & TurkishSoap",
	"AWAR & El Tyranos",
	"AWAR & I44",
	"AWAR & IFA3 Team",
	"AWAR & Joarius",
	"AWAR & Jove Chiere",
	"AWAR & Lawz",
	"AWAR & Lennard",
	"AWAR & Shvetz",
	"AWAR & Snippers",
	"AWAR & Stadl0r",
	"AWAR & swurvin",
	"AWAR",
	"bax",
	"Beton",
	"BI & Jones",
	"BI & Lennard",
	"BI & Jones & swurvin",
	"Crotmoul",
	"CSA38",
	"community upgrade project",
	"Diabolical",
	"El Tyranos & Jove Chiere",
	"El Tyranos & Lennard",
	"El Tyranos",
	"El Tyranos, Pazel",
	"French baguettes Crotmoul and El Tyranos",
	"GSTAVO",
	"I44 and IFA3 Team",
	"I44 & IFA3 Teams",
	"I44 & RJW",
	"Invasion 1944 Team & RJW",
	"I44 and El Tyranos",
	"I44",
	"invasion 1944 team",
	"IFA3 team",
	"IFA3 Team",
	"Joarius",
	"Jove Chiere & El Tyranos",
	"Jove Chiere",
	"Justin N. / swurvin",
	"Justin N.",
	"Justin",
	"Kutejnikov",
	"lawz",
	"LEN",
	"Lennard & El Tyranos",
	"Lennard",
	"Luchador, El Tyranos",
	"OPX",
	"Rauenhofer",
	"Reyhard & Joarius",
	"RJW",
	"Snippers",
	"Stadl0r",
	"Stagler",
	"swurvin & Invasion 1944 team",
	"Swurvin",
	"tierprot & [TF]Nkey & TurkishSoap",
	"tierprot & El Tyranos",
	"tierprot",
	"TurkishSoap",
	"ZVER, El Tyranos",
	"CUP",
	"CWA (Mondkalb)",
	"CWA",
	"Mondkalb"
];

TEST_IncludedAuthors = TEST_IncludedAuthors apply {toLower _x};

call compile preprocessFileLineNumbers "createRadioProtocolDefinition.sqf";

endLoadingScreen;

endMission "END1";
